apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: falco

resources:
  - falco-daemonset.yaml
  - falco-configmap.yaml
  - falco-sa.yaml
  - falcosidekick.yaml
  - falcosidekick-svc.yaml

